spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chargegrid_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # SQL formatting on console
    show-sql: true # Shows the SQL queries that Hibernate makes under the hood